# Generated by Django 5.1.3 on 2025-05-12 09:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.CharField(max_length=150)),
                ("websitelink", models.CharField(max_length=50)),
                ("gitHubRepo", models.CharField(max_length=100)),
                (
                    "site_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("create_at", models.DateTimeField(auto_now=True)),
                ("update_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="websites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "website",
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bugArea", models.CharField(max_length=200)),
                ("priority", models.CharField(max_length=50)),
                ("IssueDetail", models.TextField()),
                ("Device", models.CharField(max_length=50)),
                ("Browse", models.CharField(max_length=50)),
                ("OperatingSystem", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Issuecreator.website",
                    ),
                ),
            ],
            options={
                "db_table": "issue",
            },
        ),
    ]
