# Generated by Django 5.1.3 on 2025-04-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.CharField(max_length=150)),
                ("websitelink", models.CharField(max_length=20)),
                ("gitHubRepo", models.TextField()),
                ("create_at", models.DateTimeField(auto_now=True)),
                ("update_at", models.DateTimeField(auto_now_add=True)),
                ("feedback", models.TextField()),
            ],
        ),
    ]
