# Generated by Django 5.1.3 on 2025-04-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Issuecreator", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Issue",
            new_name="Website",
        ),
    ]
