# Generated by Django 5.1.3 on 2025-04-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Issuecreator", "0002_rename_issue_website"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="website",
            name="feedback",
        ),
        migrations.AlterField(
            model_name="website",
            name="gitHubRepo",
            field=models.CharField(max_length=50),
        ),
    ]
