# Generated by Django 5.1.3 on 2025-04-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Issuecreator", "0003_remove_website_feedback_alter_website_githubrepo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bugArea", models.CharField(max_length=200)),
                ("priority", models.TextField()),
                ("IssueDetail", models.CharField(max_length=150)),
                ("Device", models.CharField(max_length=50)),
                ("Browse", models.CharField(max_length=100)),
                ("OperatingSystem", models.CharField(max_length=100)),
            ],
        ),
    ]
