# Generated by Django 4.2.7 on 2025-05-03 19:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Issuecreator', '0004_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='site_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='gitHubRepo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='website',
            name='websitelink',
            field=models.CharField(max_length=50),
        ),
    ]
