# Generated by Django 4.2.7 on 2025-05-03 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Issuecreator', '0005_website_site_key_alter_website_githubrepo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='Issuecreator.website'),
        ),
        migrations.AddField(
            model_name='website',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL),
        ),
    ]
